config {
    type: "incremental",
    tags: [dataform.projectConfig.vars.environment, "aggregate-analytics"],
    database: dataform.projectConfig.vars.source_database,
    schema: dataform.projectConfig.vars.target_aggregated_dataset,
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
        updatePartitionFilter: "event_date = partition_event_date"
    },
    uniqueKey: ["event_date", "cleaned_page_location"],
    dependOnDependencyAssertions: true
}

pre_operations {
  DECLARE partition_event_date DATE;
  SET partition_event_date = (
    SELECT MIN(event_date)
    FROM  ${ref("staging_page_summaries")}
    );
}

SELECT *
FROM ${ref("staging_page_summaries")}
