config {
    type: "incremental",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.source_database,
    schema: dataform.projectConfig.vars.target_flattened_dataset,
    dependencies: [ "ga4_partition_assertions"],
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
        clusterBy: ["event_name"]
    }  
}
 
SELECT 
  *
FROM ${ref("ga4_augmenting")}