config {
    type: "incremental",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.source_database,
    schema: dataform.projectConfig.vars.target_flattened_dataset,
    bigquery: {
        partitionBy: "event_date",
        requirePartitionFilter : true,
        updatePartitionFilter: "event_date = partition_event_date"
    },
    uniqueKey: [
      "event_date",
      "event_type",
      "search_start_page",
      "search_term",
      "search_page",
      "search_destination_page"
    ],
    dependOnDependencyAssertions: true
}

pre_operations {
  DECLARE partition_event_date DATE;
  SET partition_event_date = (
    SELECT MIN(event_date)
    FROM  ${ref("staging_search_events")}
    );
}

SELECT *
FROM ${ref("staging_search_events")}
