config {
    type: "table",
    tags: [dataform.projectConfig.vars.environment],
    database: dataform.projectConfig.vars.processing_database,
    schema: dataform.projectConfig.vars.processing_schema,
    assertions: {
        uniqueKey: [
            "event_date",
            "event_name",
            "cleaned_page_location",
            "canonical_url",
            "link_domain",
            "link_url",
            "type",
            "outbound"
        ]
    }
}

SELECT
 event_date,
 event_name,
 cleaned_page_location,
 COALESCE(canonical_url, '') AS canonical_url,
 COALESCE(link_domain, '') AS link_domain,
 COALESCE(link_url, '') AS link_url,
 COALESCE(type, '') AS type,
 COALESCE(outbound, '') AS outbound,
 COUNT(*) AS event_count,
 COUNT(DISTINCT unique_session_id) AS sessions_with_event
FROM ${ref("ga4_augmenting")}
WHERE
 event_name IN ('navigation', 'information_click', 'file_download')
GROUP BY
 event_date,
 event_name,
 cleaned_page_location,
 canonical_url,
 link_domain,
 link_url,
 type,
 outbound
