config {
  type: "assertion",
  tags: [dataform.projectConfig.vars.environment],
  database: dataform.projectConfig.vars.processing_database
}

WITH dates_to_process AS (
  SELECT DISTINCT
    SAFE.PARSE_DATE('%Y%m%d', table_name) AS event_date
  FROM ${ref("ga4_process_shard")}
  WHERE table_name IS NOT NULL
),

existing_target_partitions AS (
  SELECT DISTINCT
    SAFE.PARSE_DATE('%Y%m%d', partition_id) AS event_date
  FROM `${dataform.projectConfig.vars.source_database}.${dataform.projectConfig.vars.target_flattened_dataset}.INFORMATION_SCHEMA.PARTITIONS`
  WHERE table_name = 'partitioned_flattened_events'
    AND partition_id IS NOT NULL
    AND partition_id != '__NULL__'
    AND total_rows > 0
)

SELECT
  processing.event_date
FROM dates_to_process AS processing
INNER JOIN existing_target_partitions AS existing
  ON processing.event_date = existing.event_date
WHERE processing.event_date IS NOT NULL

